"""Small Streamlit demo for the frozen Harmonic Fingerprint classifier."""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path

import joblib
import pandas as pd
import streamlit as st

ROOT = Path(__file__).resolve().parent
SCRIPTS = ROOT / "scripts"
MODEL_PATH = ROOT / "model" / "random_forest_baseline.pkl"
REFERENCE_ROOT = ROOT / "data" / "real_reference"
DISPLAY_CLASSES = ("major", "minor", "ninth", "diminished")
DISPLAY_NAMES = {
    "major": "Major",
    "minor": "Minor",
    "ninth": "Ninth",
    "diminished": "Diminished",
}
EMOTION_PROFILES = {
    "major": [
        ("Simple", 43),
        ("Bright", 42),
        ("Stable", 41),
        ("Fun", 35),
    ],
    "minor": [
        ("Sad", 40),
        ("Dark", 37),
        ("Bittersweet", 35),
    ],
    "ninth": [
        ("Jazzy", 34),
        ("Stylish", 32),
        ("Attractive", 28),
    ],
    "diminished": [
        ("Dark", 36),
        ("Eerie", 35),
        ("Fear", 30),
    ],
}
PARTICIPANT_COUNT = 50

sys.path.insert(0, str(SCRIPTS))
from extract_features import extract_features  # noqa: E402


@st.cache_resource
def load_model() -> dict:
    return joblib.load(MODEL_PATH)


def predict(path: Path, artifact: dict) -> tuple[str, dict[str, float]]:
    classifier = artifact["classifier"]
    features = extract_features(path)
    probabilities = classifier.predict_proba(features.reshape(1, -1))[0]
    probabilities_by_class = {
        str(label): float(probability)
        for label, probability in zip(classifier.classes_, probabilities)
    }
    ordered_probabilities = {
        category: probabilities_by_class[category] for category in DISPLAY_CLASSES
    }
    prediction = max(ordered_probabilities, key=ordered_probabilities.get)
    return prediction, ordered_probabilities


def display_emotion_profile(prediction: str) -> None:
    st.subheader("Participant Emotion Profile")
    st.caption(
        "These emotion percentages come from participant responses in the "
        "Harmonic Fingerprint experiment. They are not generated by the chord "
        "classifier itself."
    )
    emotion_table = pd.DataFrame(
        {
            "Emotion": [emotion for emotion, _ in EMOTION_PROFILES[prediction]],
            "Percentage": [
                count / PARTICIPANT_COUNT for _, count in EMOTION_PROFILES[prediction]
            ],
        }
    ).set_index("Emotion")
    st.dataframe(
        emotion_table.style.format({"Percentage": "{:.0%}"}),
        use_container_width=True,
    )
    st.bar_chart(emotion_table, y="Percentage")


def main() -> None:
    st.set_page_config(page_title="Harmonic Fingerprint AI", page_icon="🎵")
    st.title("Harmonic Fingerprint AI")
    st.caption("Frozen Random Forest demo")

    try:
        artifact = load_model()
    except Exception as error:
        st.error(f"Could not load the frozen model: {error}")
        st.stop()

    selected_name = st.selectbox(
        "Reference sound",
        [DISPLAY_NAMES[category] for category in DISPLAY_CLASSES],
    )
    selected_category = next(
        category for category, name in DISPLAY_NAMES.items() if name == selected_name
    )
    reference_path = REFERENCE_ROOT / f"{selected_category}.wav"
    uploaded_file = st.file_uploader("Optional WAV upload", type=["wav"])

    audio_path = reference_path
    if uploaded_file is not None:
        with tempfile.NamedTemporaryFile(suffix=".wav") as temporary_file:
            temporary_file.write(uploaded_file.getvalue())
            temporary_file.flush()
            audio_path = Path(temporary_file.name)
            st.audio(uploaded_file.getvalue(), format="audio/wav")
            predict_clicked = st.button("Predict Chord", type="primary")
            if predict_clicked:
                try:
                    prediction, probabilities = predict(audio_path, artifact)
                except Exception as error:
                    st.error(f"Could not extract features or predict this WAV: {error}")
                else:
                    st.subheader("AI Chord Prediction")
                    st.success(f"Prediction: {prediction.upper()}")
                    probability_table = pd.DataFrame(
                        {
                            "Chord": [DISPLAY_NAMES[category] for category in DISPLAY_CLASSES],
                            "Probability": [probabilities[category] for category in DISPLAY_CLASSES],
                        }
                    ).set_index("Chord")
                    st.dataframe(
                        probability_table.style.format({"Probability": "{:.1%}"}),
                        use_container_width=True,
                    )
                    st.bar_chart(probability_table, y="Probability")
                    display_emotion_profile(prediction)
        return

    if not reference_path.exists():
        st.error(f"Reference WAV not found: {reference_path}")
        st.stop()

    st.audio(reference_path.read_bytes(), format="audio/wav")
    if st.button("Predict Chord", type="primary"):
        try:
            prediction, probabilities = predict(reference_path, artifact)
        except Exception as error:
            st.error(f"Could not extract features or predict this WAV: {error}")
        else:
            st.subheader("AI Chord Prediction")
            st.success(f"Prediction: {prediction.upper()}")
            probability_table = pd.DataFrame(
                {
                    "Chord": [DISPLAY_NAMES[category] for category in DISPLAY_CLASSES],
                    "Probability": [probabilities[category] for category in DISPLAY_CLASSES],
                }
            ).set_index("Chord")
            st.dataframe(
                probability_table.style.format({"Probability": "{:.1%}"}),
                use_container_width=True,
            )
            st.bar_chart(probability_table, y="Probability")
            display_emotion_profile(prediction)


if __name__ == "__main__":
    main()
